### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by ErikSom** [Birch-san/box2d-wasm#30]
Would it be possible to get in contact regarding your work on Box2D web? I would like to propose something. Kind regards, Erik

**Comment by Birch-san** [comment]
heyo, is it something appropriate for [Discussions](https://github.com/Birch-san/box2d-wasm/discussions)?

otherwise, could direct-message me on Twitter?

<a href="https://twitter.com/intent/follow?screen_name=Birchlabs">
  <img src="https://img.shields.io/twitter/follow/Birchlabs.svg?style=social&logo=twitter"/>
</a>

**Comment by ErikSom** [comment]
Thanks, I'm following you now on twitter, I'm https://twitter.com/ErikSombroek, I'm not able to DM you, I think you need to follow me first. Please feel free to delete this issue as it is not relevant for your repo, I saw no other way to reach out.
