### ISSUE TITLE
 Convex shapes are not supported 

### ISSUE THREAD

**Issue by a6965921** [Birch-san/box2d-wasm#43]
Convex shapes are not supported

`const square = new b2PolygonShape();
  var vArray = [new b2Vec2(0,-20),new b2Vec2(25,0),new b2Vec2(15,30),new b2Vec2(-15,30),new b2Vec2(-25,0)]
  square.Set(vArray, 4);`

**Comment by Ziriax** [comment]
That is by design, Box2D doesn't support that for you.

I'm not an expert, but a Google search reveals the following:

See https://github.com/erincatto/Box2D/issues/513

See also https://stackoverflow.com/questions/41515307/box2d-why-not-concave-shapes

See also http://masc.cs.gmu.edu/wiki/Box2d


Or search on NPM for [convex decomposition](https://www.npmjs.com/search?q=convex%20decomposition)

**Comment by a6965921** [comment]
Looking forward to your writing a demo

**Comment by Birch-san** [comment]
@Ziriax has helped sufficiently already.

box2d-wasm is a _bindings_ library, with no goal of adding functionality to Box2D (which is in any case [closed to contributions](https://github.com/erincatto/Box2D/issues/395#issuecomment-215931139)).
