### ISSUE TITLE
Is box2d wasm better than matterjs

### ISSUE THREAD

**Issue by a6965921** [Birch-san/box2d-wasm#45]
Is box2d wasm better than matterjs   I use matterjs  FPS is very low

**Comment by Birch-san** [comment]
I'm not familiar with matter.js, but:

https://github.com/liabru/matter-js/issues/608
> the result is not good enough  
> There are many rect-boxes are overlap .

certainly, when I play with matter.js demos: it's very easy to make objects intersect. I think Box2D is more accurate.

as for performance: I expect box2d-wasm and box2d.js to be faster than matter.js, because of access to better memory-management techniques. box2d-wasm/box2d.js are written in C++; most of the work executes in WebAssembly/asm.js. allocated objects are not reference-counted, so you don't incur garbage collection costs. moreover, objects internally are allocated with a custom block allocator, which reduces memory fragmentation and keeps the heap small (reducing memory costs and improving locality of reference).

as for features: Box2D has more types of joints:  
https://github.com/liabru/matter-js/issues/472

it sounds like matter.js _approximates_ circles:  
https://github.com/liabru/matter-js/issues/615

box2d-wasm's [`liquidfun-wasm` release](https://github.com/Birch-san/box2d-wasm#alternative-distributions) adds the fluid simulation and soft-body capabilities from [Google liquidfun](http://google.github.io/liquidfun/). demo [here](https://birchlabs.co.uk/liquidfun-wasm/).
