### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by hutzlibu** [Birch-san/box2d-wasm#7]
Since the usage of the generated code is quite different from the original API of Box2D, some documentation would be helpfull.
I just noticed, you use the wiki and added a entry about collision helpers, maybe make a note on the main Readme to link there?
(I seldom see a project use wiki)

Anyway, I can probably help a bit with documentation, I don't have much time, though, but sharing bits of code with some explenation, I can do. 

For example I just got raycast to work, like it should - and since this was not at all straight forward, I could save others the trouble.
So, would you like contributions in that regard?
If so, how?
I cannot edit the wiki, would this also work with pullrequests? (not really used to work with Github) Or just email you? Or open a issue, like this?

Anyway, heres the code about the raycast:

~~~
// preparing the callback
const _callback = new box2D.JSRayCastCallback();
 _callback.ReportFixture = function(fixture, point, normal, fraction) {
         // all the parameters come as pointers, but we want the real object
          const f = box.wrapPointer(fixture, box2D.b2Fixture);
          const p = box.wrapPointer(point, box2D.b2Vec2);
          const n = box.wrapPointer(normal, box2D.b2Vec2);
           console.log(f);

        }
// then later, do the raycast
world.RayCast(_callback,point1,point2)

**Comment by Birch-san** [comment]
> some documentation would be helpful

totally agree. 🙂 documentation is the next big thing that box2d-wasm needs.

I'm still discovering the functionality myself.  
[box2d.js](https://github.com/kripken/box2d.js/)'s demos and documentation have been useful to me.  
Box2D v2.3.1->v2.4.1 [changes some interfaces](https://github.com/Birch-san/box2d-wasm/commit/53b2283018165268f7b0c862c145203f60811ca3#diff-755953e4e4ba9eb0dfa441ab7b6eff42a6e32ae1b3c630f81cdac56cb5c99f40), but they're broadly compatible.

the docs in the current Wiki describe new features box2d-wasm exposes (that weren't previously exposed in box2d.js, due to limitations of the WebIDL binder).

> I seldom see a project use wiki

yeah, I'd worried about this. it needs linking to. in any case: I think I've created a situation that limits collaboration.

I'd like to move the current Wiki's contents into a folder of READMEs, where it can be version-controlled, and so that collaborators can contribute pull requests.

> would you like contributions in that regard?  
> If so, how?

absolutely. I want it to be convenient for people to contribute documentation, so I'm happy to accept submissions in whichever way is easy for you.

submitting snippets as issues like this works well for me (i.e. I can integrate the snippets into the docs in a standard style, then close the issue). could use a naming convention for docs issues: `[Doc] JSRayCastCallback`.

once a standard layout and style emerge, I think I'd be happy to accept pull requests that match that standard.

for now: thanks for this, and I'll try to integrate it into the docs more formally soon. 🙂

**Comment by hutzlibu** [comment]
It probably would make sense, to use the Readme of 
https://github.com/kripken/box2d.js/
as a start. And then adjust to the recent version and changes.

**Comment by Birch-san** [comment]
Thanks @hutzlibu; I've written up your raycasting docs [here](https://github.com/Birch-san/box2d-wasm/blob/master/docs/raycasting.md), and have made a new [docs folder](https://github.com/Birch-san/box2d-wasm/tree/master/docs), with links to box2d.js and Box2D's docs.

**Comment by hutzlibu** [comment]
Good job. Looks good.

I am done porting my old project btw. and start feeling comfortable now to work with wasm and make steady progress.

Once I publish my (open source) game, I can send the link, as as a showcase, what can be done with this libary ;)

(might take some more weeks, if not months, though)
